## Datos faltantes - Datos Nulos
Existen 2 formas de verificar si los datos están o no. Pandas maneja 2, si el dato está disponible o si es nulo.
Para saber si es nulo utilizo el método
### isna()

In [2]:
import pandas as pd

In [3]:
path = "./datasets/Online_Retail.csv"
retail_data = pd.read_csv(path, encoding='latin-1')
retail_data.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom

In [4]:
missing_data =  retail_data.isna()
missing_data.head(4)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False

## Contar de cada columna cuantos datos faltan
Esto se logra utilizando tambien isna() pero agregamos sum()
isna().sum()

In [9]:
missing_data_count = retail_data.isna().sum()
print("Conteo de datos faltantes por columna:\n",missing_data_count)

Conteo de datos faltantes por columna:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

# Qué pasa si existen datos faltantes, cómo los manejo? Debo eliminar las filas o mejor utilizo otra estrategia?
Para el ejemplo de abajo va a eliminar las columnas con datos faltantes.
PERO OJO ESTO NO ES UNA BUENA PRACTICA

In [11]:
# axis = 1, me indica que borra la columna
no_missing_data = retail_data.dropna(axis=1)
print("Datos sin filas con valores faltantes: \n", no_missing_data)
no_missing_data.head(2)

Datos sin filas con valores faltantes:
        InvoiceNo StockCode  Quantity    InvoiceDate  UnitPrice         Country
0         536365    85123A         6   12/1/10 8:26       2.55  United Kingdom
1         536365     71053         6   12/1/10 8:26       3.39  United Kingdom
2         536365    84406B         8   12/1/10 8:26       2.75  United Kingdom
3         536365    84029G         6   12/1/10 8:26       3.39  United Kingdom
4         536365    84029E         6   12/1/10 8:26       3.39  United Kingdom
...          ...       ...       ...            ...        ...             ...
541904    581587     22613        12  12/9/11 12:50       0.85          France
541905    581587     22899         6  12/9/11 12:50       2.10          France
541906    581587     23254         4  12/9/11 12:50       4.15          France
541907    581587     23255         4  12/9/11 12:50       4.15          France
541908    581587     22138         3  12/9/11 12:50       4.95          France

[541909 rows x 6 columns]

  InvoiceNo StockCode  Quantity   InvoiceDate  UnitPrice         Country
0    536365    85123A         6  12/1/10 8:26       2.55  United Kingdom
1    536365     71053         6  12/1/10 8:26       3.39  United Kingdom

# Rellenar los datos faltantes con el valor 0
## .fillna(0)

In [12]:
# Rellenar valores con 0
retail_data_filled_zeros = retail_data.fillna(0)
sum_zero_data = retail_data_filled_zeros.isna().sum()
print(sum_zero_data)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

## Rellenar los datos faltantes pero utilizando una técnica estadística
Ejemplo, hayando la media de la columna si es un dato numérico
* lo que debo hacer primero es calcular la media .mean()
* Después indicando la columna['tu-columna'].fillna(el-valor)

In [13]:
mean_unit_prices = retail_data['UnitPrice'].mean()
retail_data_filled_mean = retail_data['UnitPrice'].fillna(mean_unit_prices)
print(retail_data_filled_mean)

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 541909, dtype: float64