Manipulación de columnas

In [13]:
import pandas as pd
pd.set_option('display.max_columns', None) # Ver todas las columnas [2]
pd.set_option('display.width', 1000)      # Ajustar ancho de visualización

In [14]:
path = "./datasets/Online_Retail.csv"
df = pd.read_csv(path, encoding="latin-1")
df.head(2)

  InvoiceNo StockCode                         Description  Quantity   InvoiceDate  UnitPrice  CustomerID         Country
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6  12/1/10 8:26       2.55     17850.0  United Kingdom
1    536365     71053                 WHITE METAL LANTERN         6  12/1/10 8:26       3.39     17850.0  United Kingdom

In [15]:
df["Total_price"] = df['Quantity'] * df["UnitPrice"]
df.head(5)

  InvoiceNo StockCode                          Description  Quantity   InvoiceDate  UnitPrice  CustomerID         Country  Total_price
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6  12/1/10 8:26       2.55     17850.0  United Kingdom        15.30
1    536365     71053                  WHITE METAL LANTERN         6  12/1/10 8:26       3.39     17850.0  United Kingdom        20.34
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8  12/1/10 8:26       2.75     17850.0  United Kingdom        22.00
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6  12/1/10 8:26       3.39     17850.0  United Kingdom        20.34
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6  12/1/10 8:26       3.39     17850.0  United Kingdom        20.34

In [16]:
df['HighValues'] = df['Total_price'] > 20
print(df['HighValues'].head(3))

0    False
1     True
2     True
Name: HighValues, dtype: bool

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   Total_price  541909 non-null  float64
 9   HighValues   541909 non-null  bool
dtypes: bool(1), float64(3), int64(1), str(5)
memory usage: 70.9 MB

## Cambiar el formato --> Ejemplo pasar un str a un tipo datime
PAra este caso utilizamos como ejemplo la columna InvoiceDate que es de tipo str y con la función de panda to_datime() realizamos la manipulación

In [20]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
 8   Total_price  541909 non-null  float64
 9   HighValues   541909 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 64.2 MB
None

# Cambio utilizando lambda

In [22]:
df['DiscountedPrice'] = df['UnitPrice'].apply(lambda x: x* 0.9)
df.head(3)

  InvoiceNo StockCode                         Description  Quantity         InvoiceDate  UnitPrice  CustomerID         Country  Total_price  HighValues  DiscountedPrice
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6 2010-12-01 08:26:00       2.55     17850.0  United Kingdom        15.30       False            2.295
1    536365     71053                 WHITE METAL LANTERN         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34        True            3.051
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8 2010-12-01 08:26:00       2.75     17850.0  United Kingdom        22.00        True            2.475

# Aplicar una función a cada una de nuestras filas
Nuevamente utilizamos la función apply

In [28]:
def categorize_price(price):
  if price > 20:
    return 'High'
  elif price > 10 and price <= 20:
    return 'Medium'
  else:
    return 'Low'

df['PriceCategory'] = df['Total_price'].apply(categorize_price)
df.head(10)

  InvoiceNo StockCode                          Description  Quantity         InvoiceDate  UnitPrice  CustomerID         Country  Total_price  HighValues  DiscountedPrice PriceCategory
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6 2010-12-01 08:26:00       2.55     17850.0  United Kingdom        15.30       False            2.295        Medium
1    536365     71053                  WHITE METAL LANTERN         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34        True            3.051          High
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8 2010-12-01 08:26:00       2.75     17850.0  United Kingdom        22.00        True            2.475          High
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34        True            3.051          High
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom        20.34        True            3.051          High
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2 2010-12-01 08:26:00       7.65     17850.0  United Kingdom        15.30       False            6.885        Medium
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6 2010-12-01 08:26:00       4.25     17850.0  United Kingdom        25.50        True            3.825          High
7    536366     22633               HAND WARMER UNION JACK         6 2010-12-01 08:28:00       1.85     17850.0  United Kingdom        11.10       False            1.665        Medium
8    536366     22632            HAND WARMER RED POLKA DOT         6 2010-12-01 08:28:00       1.85     17850.0  United Kingdom        11.10       False            1.665        Medium
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32 2010-12-01 08:34:00       1.69     13047.0  United Kingdom        54.08        True            1.521          High